// Sorted longest-first so regex matches prefer longer units (e.g. 'eetlepel' before 'el').
export const KNOWN_UNITS: string[] = [
  // --- Nederlands (lang naar kort) ---
  'eetlepels',
  'eetlepel',
  'theelepels',
  'theelepel',
  'milliliters',
  'milliliter',
  'deciliters',
  'deciliter',
  'centiliters',
  'centiliter',
  'kilograms',
  'kilogram',
  'pakjes',
  'pakje',
  'blikjes',
  'blikje',
  'bossen',
  'bosje',
  'snufjes',
  'snufje',
  'snuifjes',
  'snuifje',
  'scheutjes',
  'scheutje',
  'plakjes',
  'plakje',
  'plakken',
  'takjes',
  'takje',
  'stukjes',
  'stukje',
  'teentjes',
  'teentje',
  'stuks',
  'teen',
  'zakjes',
  'zakje',
  'liters',
  'liter',
  'grams',
  'gram',
  'bos',

  // --- Engels (lang naar kort) ---
  'tablespoons',
  'tablespoon',
  'teaspoons',
  'teaspoon',
  'ounces',
  'ounce',
  'pounds',
  'pound',
  'packages',
  'package',
  'bunches',
  'bunch',
  'slices',
  'slice',
  'cloves',
  'clove',
  'pieces',
  'piece',
  'pinches',
  'pinch',
  'dashes',
  'dash',
  'cans',
  'can',
  'cups',
  'cup',
  'tbsp',
  'tbs',
  'tsp',
  'lbs',
  'lb',
  'oz',
  'kg',
  'ml',
  'gr',
  'dl',
  'cl',
  'g',
  'l',

  // --- Beschrijvend / overig ---
  'whole',
  'large',
  'medium',
  'small',
  'pkg',
];

export function normalizeUnit(unit: string): string {
  return unit.toLowerCase().trim();
}

export function areUnitsCompatible(unit1: string, unit2: string): boolean {
  return normalizeUnit(unit1) === normalizeUnit(unit2);
}
