// database/seeds.ts
//
// Tien Belgische gezinsklassiekers die bij verse installatie als startset
// worden ingevoerd zodat een nieuwe gebruiker direct iets te kiezen heeft.
// De volgorde bepaalt de chronologie (createdAt loopt door zodat het eerste
// recept ook bovenaan in "recent" sortering verschijnt).

import type { RecipeInput } from '../types/recipe';
import { generateId } from '../utils/id';

function ingredient(name: string, quantity: number, unit: string) {
  return { id: generateId(), name, quantity, unit };
}

export const STARTER_RECIPES: RecipeInput[] = [
  {
    title: 'Spaghetti bolognese',
    category: 'Pasta',
    difficulty: 'easy',
    preparationTime: 10,
    cookingTime: 30,
    duration: 40,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('gehakt', 500, 'g'),
      ingredient('spaghetti', 400, 'g'),
      ingredient('tomatenpuree', 2, 'el'),
      ingredient('gezeefde tomaten', 400, 'g'),
      ingredient('ui', 1, 'stuks'),
      ingredient('knoflook', 2, 'teentjes'),
      ingredient('olijfolie', 2, 'el'),
      ingredient('italiaanse kruiden', 1, 'tl'),
      ingredient('zout', 1, 'tl'),
      ingredient('peper', 0.5, 'tl'),
    ],
    steps: [
      'Snij ui en knoflook fijn.',
      'Bak in olijfolie 3 minuten.',
      'Voeg gehakt toe en bak rul.',
      'Voeg tomatenpuree toe en bak 1 minuut mee.',
      'Voeg gezeefde tomaten en kruiden toe.',
      'Laat 20 minuten zachtjes sudderen.',
      'Kook spaghetti al dente.',
      'Serveer saus over de pasta.',
    ],
  },
  {
    title: 'Groentesoep met vermicelli',
    category: 'Soep',
    difficulty: 'easy',
    preparationTime: 15,
    cookingTime: 25,
    duration: 40,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('gemengde groenten', 500, 'g'),
      ingredient('vermicelli', 100, 'g'),
      ingredient('groentebouillon', 1.5, 'l'),
      ingredient('ui', 1, 'stuks'),
      ingredient('look', 1, 'teentje'),
      ingredient('boter', 1, 'el'),
      ingredient('peterselie', 2, 'el'),
      ingredient('zout', 1, 'tl'),
      ingredient('peper', 0.5, 'tl'),
    ],
    steps: [
      'Schil en snij groenten in blokjes.',
      'Bak ui en look in boter.',
      'Voeg bouillon toe en breng aan de kook.',
      'Voeg de groenten toe.',
      'Kook 15 minuten op middelhoog vuur.',
      'Voeg vermicelli toe en kook nog 8 minuten.',
      'Bestrooi met peterselie.',
    ],
  },
  {
    title: 'Witloof gegratineerd met hesp',
    category: 'Diner',
    difficulty: 'medium',
    preparationTime: 20,
    cookingTime: 35,
    duration: 55,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('witloof', 8, 'stuks'),
      ingredient('gekookte hesp', 8, 'plakken'),
      ingredient('geraspte kaas', 150, 'g'),
      ingredient('melk', 500, 'ml'),
      ingredient('bloem', 40, 'g'),
      ingredient('boter', 40, 'g'),
      ingredient('nootmuskaat', 0.5, 'tl'),
      ingredient('zout', 1, 'tl'),
      ingredient('peper', 0.5, 'tl'),
    ],
    steps: [
      'Kook witloof 10 minuten in gezouten water.',
      'Laat uitlekken en dep droog.',
      'Wikkel elk stronkje in een plak hesp.',
      'Leg in een ovenschaal.',
      'Smelt boter, roer bloem erin en voeg melk beetje bij beetje toe tot een gladde bechamel.',
      'Breng op smaak met nootmuskaat, zout en peper.',
      'Giet de saus over het witloof.',
      'Bestrooi met geraspte kaas.',
      'Gratineer 25 minuten op 200°C.',
    ],
  },
  {
    title: 'Pannenkoeken',
    category: 'Dessert',
    difficulty: 'easy',
    preparationTime: 10,
    cookingTime: 20,
    duration: 30,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('bloem', 250, 'g'),
      ingredient('eieren', 3, 'stuks'),
      ingredient('melk', 500, 'ml'),
      ingredient('boter', 30, 'g'),
      ingredient('zout', 1, 'snuifje'),
      ingredient('suiker', 1, 'el'),
      ingredient('vanillesuiker', 1, 'zakje'),
    ],
    steps: [
      'Smelt de boter en laat afkoelen.',
      'Mix bloem, zout, suiker en vanillesuiker.',
      'Maak een kuiltje en voeg de eieren toe.',
      'Roer geleidelijk melk en gesmolten boter door het beslag.',
      'Laat 30 minuten rusten.',
      'Bak dunne pannenkoeken in een licht ingevette pan op middelhoog vuur.',
    ],
  },
  {
    title: 'Pasta met zalm en room',
    category: 'Pasta',
    difficulty: 'easy',
    preparationTime: 5,
    cookingTime: 15,
    duration: 20,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('penne', 400, 'g'),
      ingredient('gerookte zalm', 200, 'g'),
      ingredient('room', 200, 'ml'),
      ingredient('citroen', 1, 'stuks'),
      ingredient('kappertjes', 1, 'el'),
      ingredient('peterselie', 2, 'el'),
      ingredient('zout', 1, 'tl'),
      ingredient('peper', 0.5, 'tl'),
      ingredient('olijfolie', 1, 'el'),
    ],
    steps: [
      'Kook de pasta al dente.',
      'Verhit olijfolie in een pan.',
      'Voeg room toe en laat 2 minuten inkoken.',
      'Snij zalm in reepjes en voeg toe.',
      'Knijp het citroensap erbij.',
      'Roer kappertjes en peterselie erdoor.',
      'Meng met de pasta en breng op smaak.',
    ],
  },
  {
    title: 'Chili con carne',
    category: 'Diner',
    difficulty: 'easy',
    preparationTime: 10,
    cookingTime: 40,
    duration: 50,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('rundergehakt', 500, 'g'),
      ingredient('kidney bonen', 400, 'g'),
      ingredient('gezeefde tomaten', 400, 'g'),
      ingredient('ui', 1, 'stuks'),
      ingredient('paprika', 1, 'stuks'),
      ingredient('knoflook', 2, 'teentjes'),
      ingredient('chilipoeder', 1, 'tl'),
      ingredient('komijn', 1, 'tl'),
      ingredient('paprikapoeder', 1, 'tl'),
      ingredient('olijfolie', 2, 'el'),
      ingredient('zout', 1, 'tl'),
    ],
    steps: [
      'Snipper ui, paprika en knoflook.',
      'Bak 5 minuten in olijfolie.',
      'Voeg gehakt toe en bak rul.',
      'Voeg de kruiden toe en bak 1 minuut mee.',
      'Voeg tomaten en uitgelekte bonen toe.',
      'Laat 30 minuten zachtjes sudderen op laag vuur.',
      'Serveer met rijst of brood.',
    ],
  },
  {
    title: 'Wok met kip en groenten',
    category: 'Diner',
    difficulty: 'easy',
    preparationTime: 15,
    cookingTime: 15,
    duration: 30,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('kipfilet', 600, 'g'),
      ingredient('wokgroenten', 400, 'g'),
      ingredient('sojasaus', 3, 'el'),
      ingredient('sesamolie', 1, 'el'),
      ingredient('knoflook', 2, 'teentjes'),
      ingredient('gemberpoeder', 1, 'tl'),
      ingredient('zonnebloemolie', 2, 'el'),
      ingredient('rijst', 300, 'g'),
      ingredient('maizena', 1, 'tl'),
    ],
    steps: [
      'Snij kip in reepjes en marineer 10 minuten in sojasaus en maizena.',
      'Kook ondertussen de rijst.',
      'Verhit de wok op hoog vuur met olie.',
      'Bak de kip 5 minuten.',
      'Voeg knoflook en gember toe.',
      'Voeg groenten toe en wok 5 minuten op hoog vuur.',
      'Voeg sesamolie toe en serveer over de rijst.',
    ],
  },
  {
    title: 'Aardappelpuree met gehaktballetjes',
    category: 'Diner',
    difficulty: 'medium',
    preparationTime: 20,
    cookingTime: 30,
    duration: 50,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('aardappelen', 1, 'kg'),
      ingredient('rundergehakt', 500, 'g'),
      ingredient('ei', 1, 'stuks'),
      ingredient('paneermeel', 3, 'el'),
      ingredient('melk', 100, 'ml'),
      ingredient('boter', 50, 'g'),
      ingredient('ui', 1, 'stuks'),
      ingredient('peterselie', 2, 'el'),
      ingredient('nootmuskaat', 0.5, 'tl'),
      ingredient('zout', 1, 'tl'),
      ingredient('peper', 0.5, 'tl'),
    ],
    steps: [
      'Schil en kook de aardappelen 20 minuten.',
      'Meng het gehakt met ei, paneermeel, gehakte ui, peterselie, zout en peper.',
      'Rol balletjes van 3 cm.',
      'Bak de balletjes rondom bruin in boter op middelhoog vuur, ongeveer 15 minuten totaal.',
      'Stamp de aardappelen met boter en warme melk tot een gladde puree.',
      'Breng op smaak met nootmuskaat.',
    ],
  },
  {
    title: 'Tomatensoep',
    category: 'Soep',
    difficulty: 'easy',
    preparationTime: 10,
    cookingTime: 25,
    duration: 35,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('tomaten', 800, 'g'),
      ingredient('ui', 1, 'stuks'),
      ingredient('knoflook', 1, 'teentje'),
      ingredient('groentebouillon', 500, 'ml'),
      ingredient('room', 100, 'ml'),
      ingredient('boter', 1, 'el'),
      ingredient('suiker', 1, 'tl'),
      ingredient('basilicum', 1, 'el'),
      ingredient('zout', 1, 'tl'),
      ingredient('peper', 0.5, 'tl'),
    ],
    steps: [
      'Hak ui en knoflook fijn.',
      'Bak zacht in boter.',
      'Voeg de tomaten in stukken toe.',
      'Voeg bouillon, suiker en basilicum toe.',
      'Laat 20 minuten koken.',
      'Mix glad met een staafmixer.',
      'Roer de room erdoor en breng op smaak.',
    ],
  },
  {
    title: 'Pasta pesto met kerstomaten',
    category: 'Pasta',
    difficulty: 'easy',
    preparationTime: 5,
    cookingTime: 12,
    duration: 17,
    servings: 4,
    isFavorite: false,
    allergens: [],
    ingredients: [
      ingredient('fusilli', 400, 'g'),
      ingredient('groene pesto', 150, 'g'),
      ingredient('kerstomaten', 250, 'g'),
      ingredient('pijnboompitten', 40, 'g'),
      ingredient('parmezaan', 60, 'g'),
      ingredient('basilicum', 1, 'handvol'),
      ingredient('olijfolie', 1, 'el'),
      ingredient('zout', 1, 'tl'),
      ingredient('peper', 0.5, 'tl'),
    ],
    steps: [
      'Kook de pasta al dente.',
      'Rooster de pijnboompitten droog in een pan.',
      'Halveer de kerstomaten.',
      'Giet de pasta af en bewaar 4 el kookwater.',
      'Meng pasta met pesto en kookwater tot smeuïg.',
      'Voeg de kerstomaten toe.',
      'Bestrooi met pijnboompitten, parmezaan en verse basilicum.',
    ],
  },
];
